#!/bin/bash
# Frontend to `cmake --build ...`

cd "$(dirname "$(which "$0")")"

CONFIG="Release"
TARGETS=""

case $1 in
  Debug|Develop|Release)
    CONFIG=$1
    shift
esac

if [ $# -gt 0 ]; then
  TARGETS="--target $@"
fi

for LIB in gum-maths gum-system gum-essentials gum-primitives gum-codecs gum-graphics gum-opengl gum-desktop ; do
  cmake --build ../../Build/Linux/$LIB $TARGETS
done

cmake --build ../../Build/Linux/CMake/$CONFIG --config $CONFIG $TARGETS
